package com.yongdata.taj.prepare;

public enum  Key {
    remoteip,
    host,
    x_forwarded_for,
    connection,
    content_length,
    user_agent,
    content_type,
    accept,
    referer,
    cookie,
    origin,
    accept_encoding,
    accept_language,
    upgrade_insecure_requests,
    dnt,
    if_modified_since,
    Process_interval,
    HTTP_Status_Code,
    x_marble_request_id,
    Content_Type,
    Content_Length,
    Date,
    Connection,
    Cache_Control,
    cache_control,
    Set_Cookie,
    accept_charset,
    Pragma,
    pragma,
    Expires,
    Last_Modified,
    Location
}
